### ISSUE TITLE
Documentation needed

### ISSUE THREAD

**Issue by chweesee** [AakashSharma7269/linkOSs#4] opened 2021-07-29 21:22 UTC
documentation revamp

**Comment by AakashSharma7269** [comment] 2021-07-29 21:30
Yes amogus documentation coming soon ™️

**Comment by LinkossLink** [comment] 2021-07-29 22:08
[NAB] This is a feature request.

**Comment by AakashSharma7269** [comment] 2021-07-30 07:33
No, this is an important bug which has been planned fixed

**Comment by chweesee** [comment] 2021-07-30 07:34
i've added the label just in case

**Comment by chweesee** [comment] 2021-07-30 07:34
@LinkossLink  are you happy now

**Comment by AakashSharma7269** [comment] 2021-07-30 07:36
amogos bot triaged this as p0 priority

**Comment by AakashSharma7269** [comment] 2021-08-07 09:41
Cannot reproduce, moving to verified fixed

**Closed by AakashSharma7269** 2021-08-07 09:41 UTC
Labels: documentation, enhancement, help wanted, good first issue, planned fix, feature request
