### ISSUE TITLE
too sus

### ISSUE THREAD

**Issue by fryingpanisafryingpan** [AakashSharma7269/linkOSs#3] opened 2021-07-29 21:11 UTC
**Title**
too sus
**Steps to Reproduce**
observe sus
**Expected Result**
sus
**Actual Result**
sussssssssss

**Comment by AakashSharma7269** [comment] 2021-07-29 21:11
This looks like a valid bug, might be fixed in a upcoming commit, ty

**Comment by AakashSharma7269** [comment] 2021-07-29 21:12
A quick question
by sus here, you mean linkoss right?

**Comment by fryingpanisafryingpan** [comment] 2021-07-29 21:12
yes fix pls too sus i want linkoss sus hunter badge

**Comment by AakashSharma7269** [comment] 2021-07-29 21:14
Ok tysm, will be fixed in a future branch / commit

**Comment by LinkossLink** [comment] 2021-07-29 21:16
[NAB] This is a feature request. You can suggest/upvote this at https://nowhere/feedback

**Comment by chweesee** [comment] 2021-07-29 21:16
@LinkossLink forgot the .com

**Comment by LinkossLink** [comment] 2021-07-29 21:17
You forgot it

**Comment by AakashSharma7269** [comment] 2021-07-30 07:35
Claimed fixed, needs verification
moving to claimed fix , synced to linkoss boards
hopefully no longer sus™️

**Comment by AakashSharma7269** [comment] 2021-08-01 16:19
Cannot reproduce
moving from claimed fixed to verified fix

**Closed by AakashSharma7269** 2021-08-01 16:19 UTC
Labels: bug, enhancement, good first issue, planned fix, question
